### PR TITLE
Cortex-M Port

### PR DESCRIPTION
**Pull request by tidklaas**
Hello Kelvin,

I would like to contribute this port for Cortex-M MCUs to atomthreads. It is almost completely contained to its port-directory, but I had to make one small change to the atomThreadSwitch() function. Instead of clearing  the newly scheduled in TCB's suspended flag after returning from archContextSwitch(), I clear it immediately before the function call. This should be functionally equivalent unless I missed something.

I would be happy to discuss any questions, remarks or suggestions you might have.

Best Regards,
Tido

### CODE REVIEW

**Comment by kelvinlawson** [comment]
Excellent, thanks. Is it possible to run this in something like QEMU so that I can run it here without a board?

**Comment by tidklaas** [comment]
Good question, I have not used qemu so far. There seems to exist a [fork](http://beckus.github.io/qemu_stm32/) emulating STM32 MCUs that should be able to run the binaries for the nucleo-f103rb board. I will look into it in the next couple of days.

**Comment by tidklaas** [comment]
Thanks to my mad Google skills I found the GNU ARM Eclipse fork of QEMU. It provides an emulated Nucleo-F103RB board. I added a customized "qemu" board and a minimal README on how to set up that QEMU fork and run the test suite binaries with it.

**Comment by kelvinlawson** [comment]
Nice, thanks for the quick reply. I'll try it all out here, hopefully later this week.

**Comment by tidklaas** [comment]
Have you had a look at the port yet? Is there anything you would like to have changed?

**Comment by kelvinlawson** [comment]
Sorry not had a chance to test here yet, will keep you posted

**Comment by kelvinlawson** [comment]
Got a linker failure due to missing libc_nano:

```
make all
 (ELF)       kern1.elf
/usr/lib/gcc/arm-none-eabi/4.8.2/../../../arm-none-eabi/bin/ld: cannot find -lc_nano
collect2: error: ld returned 1 exit status
```

This is using the stock arm-none-eabi from Ubuntu as described in the README (Ubuntu 14.04):
```
gcc version 4.8.2 (4.8.2-14ubuntu1+6) 
```

**Comment by tidklaas** [comment]
It looks like Ubuntu does not provide the nano version of the newlib build. If you are building for the qemu board ("BOARD=qemu") it should already link against the full blown lib. Otherwise you will have to comment out line 135 in the Makefile and uncomment line 139. Linking against the full version will add about 20kb to the generated binaries.

**Comment by kelvinlawson** [comment]
Thanks, it looks like Ubuntu's newlib added libc_nano from 14.10 onward.

I've created a Docker container with 15.04 and all the prerequisites installed including the QEMU you recommended, so that people can download the whole Atomthreads cortex-m dev environment in a box.

**Comment by kelvinlawson** [comment]
Thanks a lot, great contribution.

**Comment by tidklaas** [comment]
Thank you, too. This was a fun project.

**Pull request merged**
