### PR TITLE
C++ and AVR fixes

### PR DESCRIPTION
**Pull request by jacquesg**
This PR addresses a few small issues I've had using C++ and the AVR port, including a few missing C++ guards, the use of ```F_CPU``` instead of requiring an additional define and adding a bit more flexibility in terms of the timer choice for system ticks.

### CODE REVIEW

**Comment by kelvinlawson** [comment]
Thanks a lot for the contribution - can you please look into the continuous integration error identified by Travis: https://travis-ci.org/kelvinlawson/atomthreads/builds/266553833?utm_source=github_status&utm_medium=notification

Many thanks

**Comment by jacquesg** [comment]
Should be fixed now.

**Comment by jacquesg** [comment]
Is this ok to be merged?

**Comment by kelvinlawson** [comment]
Looks good, thanks

**Comment by jacquesg** [comment]
Thanks.

**Pull request merged**
